# Generated by Django 5.0.6 on 2024-07-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
