# Generated by Django 5.0.6 on 2024-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_vehiculos', '0002_alter_vehiculo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='year',
            field=models.IntegerField(),
        ),
    ]
